// Message type constants for client <-> server communication

const MessageTypes = {
  // Client -> Server
  CREATE_ROOM: 'CREATE_ROOM',
  JOIN_ROOM: 'JOIN_ROOM',
  LEAVE_ROOM: 'LEAVE_ROOM',
  READY_TO_START: 'READY_TO_START',
  START_GAME: 'START_GAME',
  PLAY_CARDS: 'PLAY_CARDS',
  PASS: 'PASS',
  PING: 'PING',

  // Server -> Client
  ROOM_CREATED: 'ROOM_CREATED',
  ROOM_JOINED: 'ROOM_JOINED',
  PLAYER_JOINED: 'PLAYER_JOINED',
  PLAYER_LEFT: 'PLAYER_LEFT',
  PLAYER_READY: 'PLAYER_READY',
  GAME_STARTING: 'GAME_STARTING',
  GAME_STARTED: 'GAME_STARTED',
  GAME_STATE_UPDATE: 'GAME_STATE_UPDATE',
  TURN_CHANGED: 'TURN_CHANGED',
  CARDS_PLAYED: 'CARDS_PLAYED',
  PLAYER_PASSED: 'PLAYER_PASSED',
  PLAYER_FINISHED: 'PLAYER_FINISHED',
  GAME_OVER: 'GAME_OVER',
  ERROR: 'ERROR',
  PONG: 'PONG'
};

module.exports = MessageTypes;
